<div>
    <div class="mb-4 text-sm text-gray-600">
        {{ __('Thanks for signing up! Before getting started, could you verify your email address by clicking on the link we just emailed to you? If you didn\'t receive the email, we will gladly send you another.') }}
    </div>

    @if (session('status') == 'verification-link-sent')
        <div class="mb-4 font-medium text-sm text-green-600">
            {{ __('A new verification link has been sent to the email address you provided during registration.') }}
        </div>
    @endif

    {{-- سيظهر هذا القسم فقط إذا كانت الخاصية $testVerificationLink تحتوي على قيمة (أي في بيئة local) --}}
    @if(isset($testVerificationLink) && $testVerificationLink)
        <div class="mt-8 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <h3 class="font-bold text-yellow-800 mb-2">{{ __('Testing Shortcut (TEMPORARY)') }}</h3>
            <p class="text-sm text-yellow-700 mb-3">{{ __('This button automatically uses the signed link generated by the app for local testing.') }}</p>

            <a href="{{ $testVerificationLink }}"
               class="inline-flex items-center px-4 py-2 bg-yellow-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-yellow-500 focus:outline-none focus:border-yellow-700 focus:ring focus:ring-yellow-300 active:bg-yellow-900 transition ease-in-out duration-150">
                {{ __('Verify NOW (Test)') }}
            </a>
        </div>
    @endif
    <div class="mt-4 flex items-center justify-between">
        <x-primary-button wire:click="sendVerification">
            {{ __('Resend Verification Email') }}
        </x-primary-button>

        <button wire:click="logout" type="submit" class="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {{ __('Log Out') }}
            </button>
    </div>
</div>
